<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      
        DB::table('reach_countries')->delete();

        $countries = array(

            // Records 01-99 (Afghanistan to India)

            array('country_iso' => 'AF', 'country_name' => 'Afghanistan', 'country_iso3' => 'AFG', 'country_numcode' => '4', 'country_phonecode' => '93'),
            array('country_iso' => 'AL', 'country_name' => 'Albania', 'country_iso3' => 'ALB', 'country_numcode' => '8', 'country_phonecode' => '355'),
            array('country_iso' => 'DZ', 'country_name' => 'Algeria', 'country_iso3' => 'DZA', 'country_numcode' => '12', 'country_phonecode' => '213'),
            array('country_iso' => 'AS', 'country_name' => 'American Samoa', 'country_iso3' => 'ASM', 'country_numcode' => '16', 'country_phonecode' => '1684'),
            array('country_iso' => 'AD', 'country_name' => 'Andorra', 'country_iso3' => 'AND', 'country_numcode' => '20', 'country_phonecode' => '376'),
            array('country_iso' => 'AO', 'country_name' => 'Angola', 'country_iso3' => 'AGO', 'country_numcode' => '24', 'country_phonecode' => '244'),
            array('country_iso' => 'AI', 'country_name' => 'Anguilla', 'country_iso3' => 'AIA', 'country_numcode' => '660', 'country_phonecode' => '1264'),
            array('country_iso' => 'AQ', 'country_name' => 'Antarctica', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '0'),
            array('country_iso' => 'AG', 'country_name' => 'Antigua and Barbuda', 'country_iso3' => 'ATG', 'country_numcode' => '28', 'country_phonecode' => '1268'),
            array('country_iso' => 'AR', 'country_name' => 'Argentina', 'country_iso3' => 'ARG', 'country_numcode' => '32', 'country_phonecode' => '54'),
            array('country_iso' => 'AM', 'country_name' => 'Armenia', 'country_iso3' => 'ARM', 'country_numcode' => '51', 'country_phonecode' => '374'),
            array('country_iso' => 'AW', 'country_name' => 'Aruba', 'country_iso3' => 'ABW', 'country_numcode' => '533', 'country_phonecode' => '297'),
            array('country_iso' => 'AU', 'country_name' => 'Australia', 'country_iso3' => 'AUS', 'country_numcode' => '36', 'country_phonecode' => '61'),
            array('country_iso' => 'AT', 'country_name' => 'Austria', 'country_iso3' => 'AUT', 'country_numcode' => '40', 'country_phonecode' => '43'),
            array('country_iso' => 'AZ', 'country_name' => 'Azerbaijan', 'country_iso3' => 'AZE', 'country_numcode' => '31', 'country_phonecode' => '994'),
            array('country_iso' => 'BS', 'country_name' => 'Bahamas', 'country_iso3' => 'BHS', 'country_numcode' => '44', 'country_phonecode' => '1242'),
            array('country_iso' => 'BH', 'country_name' => 'Bahrain', 'country_iso3' => 'BHR', 'country_numcode' => '48', 'country_phonecode' => '973'),
            array('country_iso' => 'BD', 'country_name' => 'Bangladesh', 'country_iso3' => 'BGD', 'country_numcode' => '50', 'country_phonecode' => '880'),
            array('country_iso' => 'BB', 'country_name' => 'Barbados', 'country_iso3' => 'BRB', 'country_numcode' => '52', 'country_phonecode' => '1246'),
            array('country_iso' => 'BY', 'country_name' => 'Belarus', 'country_iso3' => 'BLR', 'country_numcode' => '112', 'country_phonecode' => '375'),
            array('country_iso' => 'BE', 'country_name' => 'Belgium', 'country_iso3' => 'BEL', 'country_numcode' => '56', 'country_phonecode' => '32'),
            array('country_iso' => 'BZ', 'country_name' => 'Belize', 'country_iso3' => 'BLZ', 'country_numcode' => '84', 'country_phonecode' => '501'),
            array('country_iso' => 'BJ', 'country_name' => 'Benin', 'country_iso3' => 'BEN', 'country_numcode' => '204', 'country_phonecode' => '229'),
            array('country_iso' => 'BM', 'country_name' => 'Bermuda', 'country_iso3' => 'BMU', 'country_numcode' => '60', 'country_phonecode' => '1441'),
            array('country_iso' => 'BT', 'country_name' => 'Bhutan', 'country_iso3' => 'BTN', 'country_numcode' => '64', 'country_phonecode' => '975'),
            array('country_iso' => 'BO', 'country_name' => 'Bolivia', 'country_iso3' => 'BOL', 'country_numcode' => '68', 'country_phonecode' => '591'),
            array('country_iso' => 'BA', 'country_name' => 'Bosnia and Herzegovina', 'country_iso3' => 'BIH', 'country_numcode' => '70', 'country_phonecode' => '387'),
            array('country_iso' => 'BW', 'country_name' => 'Botswana', 'country_iso3' => 'BWA', 'country_numcode' => '72', 'country_phonecode' => '267'),
            array('country_iso' => 'BV', 'country_name' => 'Bouvet Island', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '0'),
            array('country_iso' => 'BR', 'country_name' => 'Brazil', 'country_iso3' => 'BRA', 'country_numcode' => '76', 'country_phonecode' => '55'),
            array('country_iso' => 'IO', 'country_name' => 'British Indian Ocean Territory', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '246'),
            array('country_iso' => 'BN', 'country_name' => 'Brunei Darussalam', 'country_iso3' => 'BRN', 'country_numcode' => '96', 'country_phonecode' => '673'),
            array('country_iso' => 'BG', 'country_name' => 'Bulgaria', 'country_iso3' => 'BGR', 'country_numcode' => '100', 'country_phonecode' => '359'),
            array('country_iso' => 'BF', 'country_name' => 'Burkina Faso', 'country_iso3' => 'BFA', 'country_numcode' => '854', 'country_phonecode' => '226'),
            array('country_iso' => 'BI', 'country_name' => 'Burundi', 'country_iso3' => 'BDI', 'country_numcode' => '108', 'country_phonecode' => '257'),
            array('country_iso' => 'KH', 'country_name' => 'Cambodia', 'country_iso3' => 'KHM', 'country_numcode' => '116', 'country_phonecode' => '855'),
            array('country_iso' => 'CM', 'country_name' => 'Cameroon', 'country_iso3' => 'CMR', 'country_numcode' => '120', 'country_phonecode' => '237'),
            array('country_iso' => 'CA', 'country_name' => 'Canada', 'country_iso3' => 'CAN', 'country_numcode' => '124', 'country_phonecode' => '1'),
            array('country_iso' => 'CV', 'country_name' => 'Cape Verde', 'country_iso3' => 'CPV', 'country_numcode' => '132', 'country_phonecode' => '238'),
            array('country_iso' => 'KY', 'country_name' => 'Cayman Islands', 'country_iso3' => 'CYM', 'country_numcode' => '136', 'country_phonecode' => '1345'),
            array('country_iso' => 'CF', 'country_name' => 'Central African Republic', 'country_iso3' => 'CAF', 'country_numcode' => '140', 'country_phonecode' => '236'),
            array('country_iso' => 'TD', 'country_name' => 'Chad', 'country_iso3' => 'TCD', 'country_numcode' => '148', 'country_phonecode' => '235'),
            array('country_iso' => 'CL', 'country_name' => 'Chile', 'country_iso3' => 'CHL', 'country_numcode' => '152', 'country_phonecode' => '56'),
            array('country_iso' => 'CN', 'country_name' => 'China', 'country_iso3' => 'CHN', 'country_numcode' => '156', 'country_phonecode' => '86'),
            array('country_iso' => 'CX', 'country_name' => 'Christmas Island', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '61'),
            array('country_iso' => 'CC', 'country_name' => 'Cocos (Keeling) Islands', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '672'),
            array('country_iso' => 'CO', 'country_name' => 'Colombia', 'country_iso3' => 'COL', 'country_numcode' => '170', 'country_phonecode' => '57'),
            array('country_iso' => 'KM', 'country_name' => 'Comoros', 'country_iso3' => 'COM', 'country_numcode' => '174', 'country_phonecode' => '269'),
            array('country_iso' => 'CG', 'country_name' => 'Congo', 'country_iso3' => 'COG', 'country_numcode' => '178', 'country_phonecode' => '242'),
            array('country_iso' => 'CD', 'country_name' => 'Congo, the Democratic Republic of the', 'country_iso3' => 'COD', 'country_numcode' => '180', 'country_phonecode' => '242'),
            array('country_iso' => 'CK', 'country_name' => 'Cook Islands', 'country_iso3' => 'COK', 'country_numcode' => '184', 'country_phonecode' => '682'),
            array('country_iso' => 'CR', 'country_name' => 'Costa Rica', 'country_iso3' => 'CRI', 'country_numcode' => '188', 'country_phonecode' => '506'),
            array('country_iso' => 'CI', 'country_name' => 'Cote D\'Ivoire', 'country_iso3' => 'CIV', 'country_numcode' => '384', 'country_phonecode' => '225'),
            array('country_iso' => 'HR', 'country_name' => 'Croatia', 'country_iso3' => 'HRV', 'country_numcode' => '191', 'country_phonecode' => '385'),
            array('country_iso' => 'CU', 'country_name' => 'Cuba', 'country_iso3' => 'CUB', 'country_numcode' => '192', 'country_phonecode' => '53'),
            array('country_iso' => 'CY', 'country_name' => 'Cyprus', 'country_iso3' => 'CYP', 'country_numcode' => '196', 'country_phonecode' => '357'),
            array('country_iso' => 'CZ', 'country_name' => 'Czech Republic', 'country_iso3' => 'CZE', 'country_numcode' => '203', 'country_phonecode' => '420'),
            array('country_iso' => 'DK', 'country_name' => 'Denmark', 'country_iso3' => 'DNK', 'country_numcode' => '208', 'country_phonecode' => '45'),
            array('country_iso' => 'DJ', 'country_name' => 'Djibouti', 'country_iso3' => 'DJI', 'country_numcode' => '262', 'country_phonecode' => '253'),
            array('country_iso' => 'DM', 'country_name' => 'Dominica', 'country_iso3' => 'DMA', 'country_numcode' => '212', 'country_phonecode' => '1767'),
            array('country_iso' => 'DO', 'country_name' => 'Dominican Republic', 'country_iso3' => 'DOM', 'country_numcode' => '214', 'country_phonecode' => '1809'),
            array('country_iso' => 'EC', 'country_name' => 'Ecuador', 'country_iso3' => 'ECU', 'country_numcode' => '218', 'country_phonecode' => '593'),
            array('country_iso' => 'EG', 'country_name' => 'Egypt', 'country_iso3' => 'EGY', 'country_numcode' => '818', 'country_phonecode' => '20'),
            array('country_iso' => 'SV', 'country_name' => 'El Salvador', 'country_iso3' => 'SLV', 'country_numcode' => '222', 'country_phonecode' => '503'),
            array('country_iso' => 'GQ', 'country_name' => 'Equatorial Guinea', 'country_iso3' => 'GNQ', 'country_numcode' => '226', 'country_phonecode' => '240'),
            array('country_iso' => 'ER', 'country_name' => 'Eritrea', 'country_iso3' => 'ERI', 'country_numcode' => '232', 'country_phonecode' => '291'),
            array('country_iso' => 'EE', 'country_name' => 'Estonia', 'country_iso3' => 'EST', 'country_numcode' => '233', 'country_phonecode' => '372'),
            array('country_iso' => 'ET', 'country_name' => 'Ethiopia', 'country_iso3' => 'ETH', 'country_numcode' => '231', 'country_phonecode' => '251'),
            array('country_iso' => 'FK', 'country_name' => 'Falkland Islands (Malvinas)', 'country_iso3' => 'FLK', 'country_numcode' => '238', 'country_phonecode' => '500'),
            array('country_iso' => 'FO', 'country_name' => 'Faroe Islands', 'country_iso3' => 'FRO', 'country_numcode' => '234', 'country_phonecode' => '298'),
            array('country_iso' => 'FJ', 'country_name' => 'Fiji', 'country_iso3' => 'FJI', 'country_numcode' => '242', 'country_phonecode' => '679'),
            array('country_iso' => 'FI', 'country_name' => 'Finland', 'country_iso3' => 'FIN', 'country_numcode' => '246', 'country_phonecode' => '358'),
            array('country_iso' => 'FR', 'country_name' => 'France', 'country_iso3' => 'FRA', 'country_numcode' => '250', 'country_phonecode' => '33'),
            array('country_iso' => 'GF', 'country_name' => 'French Guiana', 'country_iso3' => 'GUF', 'country_numcode' => '254', 'country_phonecode' => '594'),
            array('country_iso' => 'PF', 'country_name' => 'French Polynesia', 'country_iso3' => 'PYF', 'country_numcode' => '258', 'country_phonecode' => '689'),
            array('country_iso' => 'TF', 'country_name' => 'French Southern Territories', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '0'),
            array('country_iso' => 'GA', 'country_name' => 'Gabon', 'country_iso3' => 'GAB', 'country_numcode' => '266', 'country_phonecode' => '241'),
            array('country_iso' => 'GM', 'country_name' => 'Gambia', 'country_iso3' => 'GMB', 'country_numcode' => '270', 'country_phonecode' => '220'),
            array('country_iso' => 'GE', 'country_name' => 'Georgia', 'country_iso3' => 'GEO', 'country_numcode' => '268', 'country_phonecode' => '995'),
            array('country_iso' => 'DE', 'country_name' => 'Germany', 'country_iso3' => 'DEU', 'country_numcode' => '276', 'country_phonecode' => '49'),
            array('country_iso' => 'GH', 'country_name' => 'Ghana', 'country_iso3' => 'GHA', 'country_numcode' => '288', 'country_phonecode' => '233'),
            array('country_iso' => 'GI', 'country_name' => 'Gibraltar', 'country_iso3' => 'GIB', 'country_numcode' => '292', 'country_phonecode' => '350'),
            array('country_iso' => 'GR', 'country_name' => 'Greece', 'country_iso3' => 'GRC', 'country_numcode' => '300', 'country_phonecode' => '30'),
            array('country_iso' => 'GL', 'country_name' => 'Greenland', 'country_iso3' => 'GRL', 'country_numcode' => '304', 'country_phonecode' => '299'),
            array('country_iso' => 'GD', 'country_name' => 'Grenada', 'country_iso3' => 'GRD', 'country_numcode' => '308', 'country_phonecode' => '1473'),
            array('country_iso' => 'GP', 'country_name' => 'Guadeloupe', 'country_iso3' => 'GLP', 'country_numcode' => '312', 'country_phonecode' => '590'),
            array('country_iso' => 'GU', 'country_name' => 'Guam', 'country_iso3' => 'GUM', 'country_numcode' => '316', 'country_phonecode' => '1671'),
            array('country_iso' => 'GT', 'country_name' => 'Guatemala', 'country_iso3' => 'GTM', 'country_numcode' => '320', 'country_phonecode' => '502'),
            array('country_iso' => 'GN', 'country_name' => 'Guinea', 'country_iso3' => 'GIN', 'country_numcode' => '324', 'country_phonecode' => '224'),
            array('country_iso' => 'GW', 'country_name' => 'Guinea-Bissau', 'country_iso3' => 'GNB', 'country_numcode' => '624', 'country_phonecode' => '245'),
            array('country_iso' => 'GY', 'country_name' => 'Guyana', 'country_iso3' => 'GUY', 'country_numcode' => '328', 'country_phonecode' => '592'),
            array('country_iso' => 'HT', 'country_name' => 'Haiti', 'country_iso3' => 'HTI', 'country_numcode' => '332', 'country_phonecode' => '509'),
            array('country_iso' => 'HM', 'country_name' => 'Heard Island and Mcdonald Islands', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '0'),
            array('country_iso' => 'VA', 'country_name' => 'Holy See (Vatican City State)', 'country_iso3' => 'VAT', 'country_numcode' => '336', 'country_phonecode' => '39'),
            array('country_iso' => 'HN', 'country_name' => 'Honduras', 'country_iso3' => 'HND', 'country_numcode' => '340', 'country_phonecode' => '504'),
            array('country_iso' => 'HK', 'country_name' => 'Hong Kong', 'country_iso3' => 'HKG', 'country_numcode' => '344', 'country_phonecode' => '852'),
            array('country_iso' => 'HU', 'country_name' => 'Hungary', 'country_iso3' => 'HUN', 'country_numcode' => '348', 'country_phonecode' => '36'),
            array('country_iso' => 'IS', 'country_name' => 'Iceland', 'country_iso3' => 'ISL', 'country_numcode' => '352', 'country_phonecode' => '354'),
            array('country_iso' => 'IN', 'country_name' => 'India', 'country_iso3' => 'IND', 'country_numcode' => '356', 'country_phonecode' => '91'),


            // Records 100-199 (Indonesia to Spain)

            array('country_iso' => 'ID', 'country_name' => 'Indonesia', 'country_iso3' => 'IDN', 'country_numcode' => '360', 'country_phonecode' => '62'),
            array('country_iso' => 'IR', 'country_name' => 'Iran, Islamic Republic of', 'country_iso3' => 'IRN', 'country_numcode' => '364', 'country_phonecode' => '98'),
            array('country_iso' => 'IQ', 'country_name' => 'Iraq', 'country_iso3' => 'IRQ', 'country_numcode' => '368', 'country_phonecode' => '964'),
            array('country_iso' => 'IE', 'country_name' => 'Ireland', 'country_iso3' => 'IRL', 'country_numcode' => '372', 'country_phonecode' => '353'),
            array('country_iso' => 'IL', 'country_name' => 'Israel', 'country_iso3' => 'ISR', 'country_numcode' => '376', 'country_phonecode' => '972'),
            array('country_iso' => 'IT', 'country_name' => 'Italy', 'country_iso3' => 'ITA', 'country_numcode' => '380', 'country_phonecode' => '39'),
            array('country_iso' => 'JM', 'country_name' => 'Jamaica', 'country_iso3' => 'JAM', 'country_numcode' => '388', 'country_phonecode' => '1876'),
            array('country_iso' => 'JP', 'country_name' => 'Japan', 'country_iso3' => 'JPN', 'country_numcode' => '392', 'country_phonecode' => '81'),
            array('country_iso' => 'JO', 'country_name' => 'Jordan', 'country_iso3' => 'JOR', 'country_numcode' => '400', 'country_phonecode' => '962'),
            array('country_iso' => 'KZ', 'country_name' => 'Kazakhstan', 'country_iso3' => 'KAZ', 'country_numcode' => '398', 'country_phonecode' => '7'),
            array('country_iso' => 'KE', 'country_name' => 'Kenya', 'country_iso3' => 'KEN', 'country_numcode' => '404', 'country_phonecode' => '254'),
            array('country_iso' => 'KI', 'country_name' => 'Kiribati', 'country_iso3' => 'KIR', 'country_numcode' => '296', 'country_phonecode' => '686'),
            array('country_iso' => 'KP', 'country_name' => 'Korea, Democratic People\'s Republic of', 'country_iso3' => 'PRK', 'country_numcode' => '408', 'country_phonecode' => '850'),
            array('country_iso' => 'KR', 'country_name' => 'Korea, Republic of', 'country_iso3' => 'KOR', 'country_numcode' => '410', 'country_phonecode' => '82'),
            array('country_iso' => 'KW', 'country_name' => 'Kuwait', 'country_iso3' => 'KWT', 'country_numcode' => '414', 'country_phonecode' => '965'),
            array('country_iso' => 'KG', 'country_name' => 'Kyrgyzstan', 'country_iso3' => 'KGZ', 'country_numcode' => '417', 'country_phonecode' => '996'),
            array('country_iso' => 'LA', 'country_name' => 'Lao People\'s Democratic Republic', 'country_iso3' => 'LAO', 'country_numcode' => '418', 'country_phonecode' => '856'),
            array('country_iso' => 'LV', 'country_name' => 'Latvia', 'country_iso3' => 'LVA', 'country_numcode' => '428', 'country_phonecode' => '371'),
            array('country_iso' => 'LB', 'country_name' => 'Lebanon', 'country_iso3' => 'LBN', 'country_numcode' => '422', 'country_phonecode' => '961'),
            array('country_iso' => 'LS', 'country_name' => 'Lesotho', 'country_iso3' => 'LSO', 'country_numcode' => '426', 'country_phonecode' => '266'),
            array('country_iso' => 'LR', 'country_name' => 'Liberia', 'country_iso3' => 'LBR', 'country_numcode' => '430', 'country_phonecode' => '231'),
            array('country_iso' => 'LY', 'country_name' => 'Libyan Arab Jamahiriya', 'country_iso3' => 'LBY', 'country_numcode' => '434', 'country_phonecode' => '218'),
            array('country_iso' => 'LI', 'country_name' => 'Liechtenstein', 'country_iso3' => 'LIE', 'country_numcode' => '438', 'country_phonecode' => '423'),
            array('country_iso' => 'LT', 'country_name' => 'Lithuania', 'country_iso3' => 'LTU', 'country_numcode' => '440', 'country_phonecode' => '370'),
            array('country_iso' => 'LU', 'country_name' => 'Luxembourg', 'country_iso3' => 'LUX', 'country_numcode' => '442', 'country_phonecode' => '352'),
            array('country_iso' => 'MO', 'country_name' => 'Macao', 'country_iso3' => 'MAC', 'country_numcode' => '446', 'country_phonecode' => '853'),
            array('country_iso' => 'MK', 'country_name' => 'Macedonia, the Former Yugoslav Republic of', 'country_iso3' => 'MKD', 'country_numcode' => '807', 'country_phonecode' => '389'),
            array('country_iso' => 'MG', 'country_name' => 'Madagascar', 'country_iso3' => 'MDG', 'country_numcode' => '450', 'country_phonecode' => '261'),
            array('country_iso' => 'MW', 'country_name' => 'Malawi', 'country_iso3' => 'MWI', 'country_numcode' => '454', 'country_phonecode' => '265'),
            array('country_iso' => 'MY', 'country_name' => 'Malaysia', 'country_iso3' => 'MYS', 'country_numcode' => '458', 'country_phonecode' => '60'),
            array('country_iso' => 'MV', 'country_name' => 'Maldives', 'country_iso3' => 'MDV', 'country_numcode' => '462', 'country_phonecode' => '960'),
            array('country_iso' => 'ML', 'country_name' => 'Mali', 'country_iso3' => 'MLI', 'country_numcode' => '466', 'country_phonecode' => '223'),
            array('country_iso' => 'MT', 'country_name' => 'Malta', 'country_iso3' => 'MLT', 'country_numcode' => '470', 'country_phonecode' => '356'),
            array('country_iso' => 'MH', 'country_name' => 'Marshall Islands', 'country_iso3' => 'MHL', 'country_numcode' => '584', 'country_phonecode' => '692'),
            array('country_iso' => 'MQ', 'country_name' => 'Martinique', 'country_iso3' => 'MTQ', 'country_numcode' => '474', 'country_phonecode' => '596'),
            array('country_iso' => 'MR', 'country_name' => 'Mauritania', 'country_iso3' => 'MRT', 'country_numcode' => '478', 'country_phonecode' => '222'),
            array('country_iso' => 'MU', 'country_name' => 'Mauritius', 'country_iso3' => 'MUS', 'country_numcode' => '480', 'country_phonecode' => '230'),
            array('country_iso' => 'YT', 'country_name' => 'Mayotte', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '269'),
            array('country_iso' => 'MX', 'country_name' => 'Mexico', 'country_iso3' => 'MEX', 'country_numcode' => '484', 'country_phonecode' => '52'),
            array('country_iso' => 'FM', 'country_name' => 'Micronesia, Federated States of', 'country_iso3' => 'FSM', 'country_numcode' => '583', 'country_phonecode' => '691'),
            array('country_iso' => 'MD', 'country_name' => 'Moldova, Republic of', 'country_iso3' => 'MDA', 'country_numcode' => '498', 'country_phonecode' => '373'),
            array('country_iso' => 'MC', 'country_name' => 'Monaco', 'country_iso3' => 'MCO', 'country_numcode' => '492', 'country_phonecode' => '377'),
            array('country_iso' => 'MN', 'country_name' => 'Mongolia', 'country_iso3' => 'MNG', 'country_numcode' => '496', 'country_phonecode' => '976'),
            array('country_iso' => 'MS', 'country_name' => 'Montserrat', 'country_iso3' => 'MSR', 'country_numcode' => '500', 'country_phonecode' => '1664'),
            array('country_iso' => 'MA', 'country_name' => 'Morocco', 'country_iso3' => 'MAR', 'country_numcode' => '504', 'country_phonecode' => '212'),
            array('country_iso' => 'MZ', 'country_name' => 'Mozambique', 'country_iso3' => 'MOZ', 'country_numcode' => '508', 'country_phonecode' => '258'),
            array('country_iso' => 'MM', 'country_name' => 'Myanmar', 'country_iso3' => 'MMR', 'country_numcode' => '104', 'country_phonecode' => '95'),
            array('country_iso' => 'NA', 'country_name' => 'Namibia', 'country_iso3' => 'NAM', 'country_numcode' => '516', 'country_phonecode' => '264'),
            array('country_iso' => 'NR', 'country_name' => 'Nauru', 'country_iso3' => 'NRU', 'country_numcode' => '520', 'country_phonecode' => '674'),
            array('country_iso' => 'NP', 'country_name' => 'Nepal', 'country_iso3' => 'NPL', 'country_numcode' => '524', 'country_phonecode' => '977'),
            array('country_iso' => 'NL', 'country_name' => 'Netherlands', 'country_iso3' => 'NLD', 'country_numcode' => '528', 'country_phonecode' => '31'),
            array('country_iso' => 'AN', 'country_name' => 'Netherlands Antilles', 'country_iso3' => 'ANT', 'country_numcode' => '530', 'country_phonecode' => '599'),
            array('country_iso' => 'NC', 'country_name' => 'New Caledonia', 'country_iso3' => 'NCL', 'country_numcode' => '540', 'country_phonecode' => '687'),
            array('country_iso' => 'NZ', 'country_name' => 'New Zealand', 'country_iso3' => 'NZL', 'country_numcode' => '554', 'country_phonecode' => '64'),
            array('country_iso' => 'NI', 'country_name' => 'Nicaragua', 'country_iso3' => 'NIC', 'country_numcode' => '558', 'country_phonecode' => '505'),
            array('country_iso' => 'NE', 'country_name' => 'Niger', 'country_iso3' => 'NER', 'country_numcode' => '562', 'country_phonecode' => '227'),
            array('country_iso' => 'NG', 'country_name' => 'Nigeria', 'country_iso3' => 'NGA', 'country_numcode' => '566', 'country_phonecode' => '234'),
            array('country_iso' => 'NU', 'country_name' => 'Niue', 'country_iso3' => 'NIU', 'country_numcode' => '570', 'country_phonecode' => '683'),
            array('country_iso' => 'NF', 'country_name' => 'Norfolk Island', 'country_iso3' => 'NFK', 'country_numcode' => '574', 'country_phonecode' => '672'),
            array('country_iso' => 'MP', 'country_name' => 'Northern Mariana Islands', 'country_iso3' => 'MNP', 'country_numcode' => '580', 'country_phonecode' => '1670'),
            array('country_iso' => 'NO', 'country_name' => 'Norway', 'country_iso3' => 'NOR', 'country_numcode' => '578', 'country_phonecode' => '47'),
            array('country_iso' => 'OM', 'country_name' => 'Oman', 'country_iso3' => 'OMN', 'country_numcode' => '512', 'country_phonecode' => '968'),
            array('country_iso' => 'PK', 'country_name' => 'Pakistan', 'country_iso3' => 'PAK', 'country_numcode' => '586', 'country_phonecode' => '92'),
            array('country_iso' => 'PW', 'country_name' => 'Palau', 'country_iso3' => 'PLW', 'country_numcode' => '585', 'country_phonecode' => '680'),
            array('country_iso' => 'PS', 'country_name' => 'Palestinian Territory, Occupied', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '970'),
            array('country_iso' => 'PA', 'country_name' => 'Panama', 'country_iso3' => 'PAN', 'country_numcode' => '591', 'country_phonecode' => '507'),
            array('country_iso' => 'PG', 'country_name' => 'Papua New Guinea', 'country_iso3' => 'PNG', 'country_numcode' => '598', 'country_phonecode' => '675'),
            array('country_iso' => 'PY', 'country_name' => 'Paraguay', 'country_iso3' => 'PRY', 'country_numcode' => '600', 'country_phonecode' => '595'),
            array('country_iso' => 'PE', 'country_name' => 'Peru', 'country_iso3' => 'PER', 'country_numcode' => '604', 'country_phonecode' => '51'),
            array('country_iso' => 'PH', 'country_name' => 'Philippines', 'country_iso3' => 'PHL', 'country_numcode' => '608', 'country_phonecode' => '63'),
            array('country_iso' => 'PN', 'country_name' => 'Pitcairn', 'country_iso3' => 'PCN', 'country_numcode' => '612', 'country_phonecode' => '0'),
            array('country_iso' => 'PL', 'country_name' => 'Poland', 'country_iso3' => 'POL', 'country_numcode' => '616', 'country_phonecode' => '48'),
            array('country_iso' => 'PT', 'country_name' => 'Portugal', 'country_iso3' => 'PRT', 'country_numcode' => '620', 'country_phonecode' => '351'),
            array('country_iso' => 'PR', 'country_name' => 'Puerto Rico', 'country_iso3' => 'PRI', 'country_numcode' => '630', 'country_phonecode' => '1787'),
            array('country_iso' => 'QA', 'country_name' => 'Qatar', 'country_iso3' => 'QAT', 'country_numcode' => '634', 'country_phonecode' => '974'),
            array('country_iso' => 'RE', 'country_name' => 'Reunion', 'country_iso3' => 'REU', 'country_numcode' => '638', 'country_phonecode' => '262'),
            array('country_iso' => 'RO', 'country_name' => 'Romania', 'country_iso3' => 'ROM', 'country_numcode' => '642', 'country_phonecode' => '40'),
            array('country_iso' => 'RU', 'country_name' => 'Russian Federation', 'country_iso3' => 'RUS', 'country_numcode' => '643', 'country_phonecode' => '70'),
            array('country_iso' => 'RW', 'country_name' => 'Rwanda', 'country_iso3' => 'RWA', 'country_numcode' => '646', 'country_phonecode' => '250'),
            array('country_iso' => 'SH', 'country_name' => 'Saint Helena', 'country_iso3' => 'SHN', 'country_numcode' => '654', 'country_phonecode' => '290'),
            array('country_iso' => 'KN', 'country_name' => 'Saint Kitts and Nevis', 'country_iso3' => 'KNA', 'country_numcode' => '659', 'country_phonecode' => '1869'),
            array('country_iso' => 'LC', 'country_name' => 'Saint Lucia', 'country_iso3' => 'LCA', 'country_numcode' => '662', 'country_phonecode' => '1758'),
            array('country_iso' => 'PM', 'country_name' => 'Saint Pierre and Miquelon', 'country_iso3' => 'SPM', 'country_numcode' => '666', 'country_phonecode' => '508'),
            array('country_iso' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines', 'country_iso3' => 'VCT', 'country_numcode' => '670', 'country_phonecode' => '1784'),
            array('country_iso' => 'WS', 'country_name' => 'Samoa', 'country_iso3' => 'WSM', 'country_numcode' => '882', 'country_phonecode' => '684'),
            array('country_iso' => 'SM', 'country_name' => 'San Marino', 'country_iso3' => 'SMR', 'country_numcode' => '674', 'country_phonecode' => '378'),
            array('country_iso' => 'ST', 'country_name' => 'Sao Tome and Principe', 'country_iso3' => 'STP', 'country_numcode' => '678', 'country_phonecode' => '239'),
            array('country_iso' => 'SA', 'country_name' => 'Saudi Arabia', 'country_iso3' => 'SAU', 'country_numcode' => '682', 'country_phonecode' => '966'),
            array('country_iso' => 'SN', 'country_name' => 'Senegal', 'country_iso3' => 'SEN', 'country_numcode' => '686', 'country_phonecode' => '221'),
            array('country_iso' => 'CS', 'country_name' => 'Serbia and Montenegro', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '381'),
            array('country_iso' => 'SC', 'country_name' => 'Seychelles', 'country_iso3' => 'SYC', 'country_numcode' => '690', 'country_phonecode' => '248'),
            array('country_iso' => 'SL', 'country_name' => 'Sierra Leone', 'country_iso3' => 'SLE', 'country_numcode' => '694', 'country_phonecode' => '232'),
            array('country_iso' => 'SG', 'country_name' => 'Singapore', 'country_iso3' => 'SGP', 'country_numcode' => '702', 'country_phonecode' => '65'),
            array('country_iso' => 'SK', 'country_name' => 'Slovakia', 'country_iso3' => 'SVK', 'country_numcode' => '703', 'country_phonecode' => '421'),
            array('country_iso' => 'SI', 'country_name' => 'Slovenia', 'country_iso3' => 'SVN', 'country_numcode' => '705', 'country_phonecode' => '386'),
            array('country_iso' => 'SB', 'country_name' => 'Solomon Islands', 'country_iso3' => 'SLB', 'country_numcode' => '90', 'country_phonecode' => '677'),
            array('country_iso' => 'SO', 'country_name' => 'Somalia', 'country_iso3' => 'SOM', 'country_numcode' => '706', 'country_phonecode' => '252'),
            array('country_iso' => 'ZA', 'country_name' => 'South Africa', 'country_iso3' => 'ZAF', 'country_numcode' => '710', 'country_phonecode' => '27'),
            array('country_iso' => 'GS', 'country_name' => 'South Georgia and the South Sandwich Islands', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '0'),
            array('country_iso' => 'ES', 'country_name' => 'Spain', 'country_iso3' => 'ESP', 'country_numcode' => '724', 'country_phonecode' => '34'),


            // Records 200-253 (Sri Lanka to South Sudan)

            array('country_iso' => 'LK', 'country_name' => 'Sri Lanka', 'country_iso3' => 'LKA', 'country_numcode' => '144', 'country_phonecode' => '94'),
            array('country_iso' => 'SD', 'country_name' => 'Sudan', 'country_iso3' => 'SDN', 'country_numcode' => '736', 'country_phonecode' => '249'),
            array('country_iso' => 'SR', 'country_name' => 'Suriname', 'country_iso3' => 'SUR', 'country_numcode' => '740', 'country_phonecode' => '597'),
            array('country_iso' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen', 'country_iso3' => 'SJM', 'country_numcode' => '744', 'country_phonecode' => '47'),
            array('country_iso' => 'SZ', 'country_name' => 'Swaziland', 'country_iso3' => 'SWZ', 'country_numcode' => '748', 'country_phonecode' => '268'),
            array('country_iso' => 'SE', 'country_name' => 'Sweden', 'country_iso3' => 'SWE', 'country_numcode' => '752', 'country_phonecode' => '46'),
            array('country_iso' => 'CH', 'country_name' => 'Switzerland', 'country_iso3' => 'CHE', 'country_numcode' => '756', 'country_phonecode' => '41'),
            array('country_iso' => 'SY', 'country_name' => 'Syrian Arab Republic', 'country_iso3' => 'SYR', 'country_numcode' => '760', 'country_phonecode' => '963'),
            array('country_iso' => 'TW', 'country_name' => 'Taiwan, Province of China', 'country_iso3' => 'TWN', 'country_numcode' => '158', 'country_phonecode' => '886'),
            array('country_iso' => 'TJ', 'country_name' => 'Tajikistan', 'country_iso3' => 'TJK', 'country_numcode' => '762', 'country_phonecode' => '992'),
            array('country_iso' => 'TZ', 'country_name' => 'Tanzania, United Republic of', 'country_iso3' => 'TZA', 'country_numcode' => '834', 'country_phonecode' => '255'),
            array('country_iso' => 'TH', 'country_name' => 'Thailand', 'country_iso3' => 'THA', 'country_numcode' => '764', 'country_phonecode' => '66'),
            array('country_iso' => 'TL', 'country_name' => 'Timor-Leste', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '670'),
            array('country_iso' => 'TG', 'country_name' => 'Togo', 'country_iso3' => 'TGO', 'country_numcode' => '768', 'country_phonecode' => '228'),
            array('country_iso' => 'TK', 'country_name' => 'Tokelau', 'country_iso3' => 'TKL', 'country_numcode' => '772', 'country_phonecode' => '690'),
            array('country_iso' => 'TO', 'country_name' => 'Tonga', 'country_iso3' => 'TON', 'country_numcode' => '776', 'country_phonecode' => '676'),
            array('country_iso' => 'TT', 'country_name' => 'Trinidad and Tobago', 'country_iso3' => 'TTO', 'country_numcode' => '780', 'country_phonecode' => '1868'),
            array('country_iso' => 'TN', 'country_name' => 'Tunisia', 'country_iso3' => 'TUN', 'country_numcode' => '788', 'country_phonecode' => '216'),
            array('country_iso' => 'TR', 'country_name' => 'Turkey', 'country_iso3' => 'TUR', 'country_numcode' => '792', 'country_phonecode' => '90'),
            array('country_iso' => 'TM', 'country_name' => 'Turkmenistan', 'country_iso3' => 'TKM', 'country_numcode' => '795', 'country_phonecode' => '7370'),
            array('country_iso' => 'TC', 'country_name' => 'Turks and Caicos Islands', 'country_iso3' => 'TCA', 'country_numcode' => '796', 'country_phonecode' => '1649'),
            array('country_iso' => 'TV', 'country_name' => 'Tuvalu', 'country_iso3' => 'TUV', 'country_numcode' => '798', 'country_phonecode' => '688'),
            array('country_iso' => 'UG', 'country_name' => 'Uganda', 'country_iso3' => 'UGA', 'country_numcode' => '800', 'country_phonecode' => '256'),
            array('country_iso' => 'UA', 'country_name' => 'Ukraine', 'country_iso3' => 'UKR', 'country_numcode' => '804', 'country_phonecode' => '380'),
            array('country_iso' => 'AE', 'country_name' => 'United Arab Emirates', 'country_iso3' => 'ARE', 'country_numcode' => '784', 'country_phonecode' => '971'),
            array('country_iso' => 'GB', 'country_name' => 'United Kingdom', 'country_iso3' => 'GBR', 'country_numcode' => '826', 'country_phonecode' => '44'),
            array('country_iso' => 'US', 'country_name' => 'United States', 'country_iso3' => 'USA', 'country_numcode' => '840', 'country_phonecode' => '1'),
            array('country_iso' => 'UM', 'country_name' => 'United States Minor Outlying Islands', 'country_iso3' => NULL,'country_numcode' => NULL,'country_phonecode' => '1'),
            array('country_iso' => 'UY', 'country_name' => 'Uruguay', 'country_iso3' => 'URY', 'country_numcode' => '858', 'country_phonecode' => '598'),
            array('country_iso' => 'UZ', 'country_name' => 'Uzbekistan', 'country_iso3' => 'UZB', 'country_numcode' => '860', 'country_phonecode' => '998'),
            array('country_iso' => 'VU', 'country_name' => 'Vanuatu', 'country_iso3' => 'VUT', 'country_numcode' => '548', 'country_phonecode' => '678'),
            array('country_iso' => 'VE', 'country_name' => 'Venezuela', 'country_iso3' => 'VEN', 'country_numcode' => '862', 'country_phonecode' => '58'),
            array('country_iso' => 'VN', 'country_name' => 'Viet Nam', 'country_iso3' => 'VNM', 'country_numcode' => '704', 'country_phonecode' => '84'),
            array('country_iso' => 'VG', 'country_name' => 'Virgin Islands, British', 'country_iso3' => 'VGB', 'country_numcode' => '92', 'country_phonecode' => '1284'),
            array('country_iso' => 'VI', 'country_name' => 'Virgin Islands, U.S.', 'country_iso3' => 'VIR', 'country_numcode' => '850', 'country_phonecode' => '1340'),
            array('country_iso' => 'WF', 'country_name' => 'Wallis and Futuna', 'country_iso3' => 'WLF', 'country_numcode' => '876', 'country_phonecode' => '681'),
            array('country_iso' => 'EH', 'country_name' => 'Western Sahara', 'country_iso3' => 'ESH', 'country_numcode' => '732', 'country_phonecode' => '212'),
            array('country_iso' => 'YE', 'country_name' => 'Yemen', 'country_iso3' => 'YEM', 'country_numcode' => '887', 'country_phonecode' => '967'),
            array('country_iso' => 'ZM', 'country_name' => 'Zambia', 'country_iso3' => 'ZMB', 'country_numcode' => '894', 'country_phonecode' => '260'),
            array('country_iso' => 'ZW', 'country_name' => 'Zimbabwe', 'country_iso3' => 'ZWE', 'country_numcode' => '716', 'country_phonecode' => '263'),
            array('country_iso' => 'RS', 'country_name' => 'Serbia', 'country_iso3' => 'SRB', 'country_numcode' => '688', 'country_phonecode' => '381'),
            array('country_iso' => 'AP', 'country_name' => 'Asia / Pacific Region', 'country_iso3' => '0', 'country_numcode' => '0', 'country_phonecode' => '0'),
            array('country_iso' => 'ME', 'country_name' => 'Montenegro', 'country_iso3' => 'MNE', 'country_numcode' => '499', 'country_phonecode' => '382'),
            array('country_iso' => 'AX', 'country_name' => 'Aland Islands', 'country_iso3' => 'ALA', 'country_numcode' => '248', 'country_phonecode' => '358'),
            array('country_iso' => 'BQ', 'country_name' => 'Bonaire, Sint Eustatius and Saba', 'country_iso3' => 'BES', 'country_numcode' => '535', 'country_phonecode' => '599'),
            array('country_iso' => 'CW', 'country_name' => 'Curacao', 'country_iso3' => 'CUW', 'country_numcode' => '531', 'country_phonecode' => '599'),
            array('country_iso' => 'GG', 'country_name' => 'Guernsey', 'country_iso3' => 'GGY', 'country_numcode' => '831', 'country_phonecode' => '44'),
            array('country_iso' => 'IM', 'country_name' => 'Isle of Man', 'country_iso3' => 'IMN', 'country_numcode' => '833', 'country_phonecode' => '44'),
            array('country_iso' => 'JE', 'country_name' => 'Jersey', 'country_iso3' => 'JEY', 'country_numcode' => '832', 'country_phonecode' => '44'),
            array('country_iso' => 'XK', 'country_name' => 'Kosovo', 'country_iso3' => '---', 'country_numcode' => '0', 'country_phonecode' => '381'),
            array('country_iso' => 'BL', 'country_name' => 'Saint Barthelemy', 'country_iso3' => 'BLM', 'country_numcode' => '652', 'country_phonecode' => '590'),
            array('country_iso' => 'MF', 'country_name' => 'Saint Martin', 'country_iso3' => 'MAF', 'country_numcode' => '663', 'country_phonecode' => '590'),
            array('country_iso' => 'SX', 'country_name' => 'Sint Maarten', 'country_iso3' => 'SXM', 'country_numcode' => '534', 'country_phonecode' => '1'),
            array('country_iso' => 'SS', 'country_name' => 'South Sudan', 'country_iso3' => 'SSD', 'country_numcode' => '728', 'country_phonecode' => '211')
          );

          DB::table('reach_countries')->insert($countries);

    }
}
