<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReachPassportTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country_name' => 'Afghanistan', 'country_iso' => 'AF', 'country_status' => 'A'],
            ['country_name' => 'Albania', 'country_iso' => 'AL', 'country_status' => 'A'],
            ['country_name' => 'Algeria', 'country_iso' => 'DZ', 'country_status' => 'A'],
            ['country_name' => 'Andorra', 'country_iso' => 'AD', 'country_status' => 'A'],
            ['country_name' => 'Angola', 'country_iso' => 'AO', 'country_status' => 'A'],
            ['country_name' => 'Antigua and Barbuda', 'country_iso' => 'AG', 'country_status' => 'A'],
            ['country_name' => 'Argentina', 'country_iso' => 'AR', 'country_status' => 'A'],
            ['country_name' => 'Armenia', 'country_iso' => 'AM', 'country_status' => 'A'],
            ['country_name' => 'Australia', 'country_iso' => 'AU', 'country_status' => 'A'],
            ['country_name' => 'Austria', 'country_iso' => 'AT', 'country_status' => 'A'],
            ['country_name' => 'Azerbaijan', 'country_iso' => 'AZ', 'country_status' => 'A'],
            ['country_name' => 'Bahamas', 'country_iso' => 'BS', 'country_status' => 'A'],
            ['country_name' => 'Bahrain', 'country_iso' => 'BH', 'country_status' => 'A'],
            ['country_name' => 'Bangladesh', 'country_iso' => 'BD', 'country_status' => 'A'],
            ['country_name' => 'Barbados', 'country_iso' => 'BB', 'country_status' => 'A'],
            ['country_name' => 'Belarus', 'country_iso' => 'BY', 'country_status' => 'A'],
            ['country_name' => 'Belgium', 'country_iso' => 'BE', 'country_status' => 'A'],
            ['country_name' => 'Belize', 'country_iso' => 'BZ', 'country_status' => 'A'],
            ['country_name' => 'Benin', 'country_iso' => 'BJ', 'country_status' => 'A'],
            ['country_name' => 'Bhutan', 'country_iso' => 'BT', 'country_status' => 'A'],
            ['country_name' => 'Bolivia', 'country_iso' => 'BO', 'country_status' => 'A'],
            ['country_name' => 'Bosnia and Herzegovina', 'country_iso' => 'BA', 'country_status' => 'A'],
            ['country_name' => 'Botswana', 'country_iso' => 'BW', 'country_status' => 'A'],
            ['country_name' => 'Brazil', 'country_iso' => 'BR', 'country_status' => 'A'],
            ['country_name' => 'Brunei', 'country_iso' => 'BN', 'country_status' => 'A'],
            ['country_name' => 'Bulgaria', 'country_iso' => 'BG', 'country_status' => 'A'],
            ['country_name' => 'Burkina Faso', 'country_iso' => 'BF', 'country_status' => 'A'],
            ['country_name' => 'Burundi', 'country_iso' => 'BI', 'country_status' => 'A'],
            ['country_name' => 'Cabo Verde', 'country_iso' => 'CV', 'country_status' => 'A'],
            ['country_name' => 'Cambodia', 'country_iso' => 'KH', 'country_status' => 'A'],
            ['country_name' => 'Cameroon', 'country_iso' => 'CM', 'country_status' => 'A'],
            ['country_name' => 'Canada', 'country_iso' => 'CA', 'country_status' => 'A'],
            ['country_name' => 'Central African Republic', 'country_iso' => 'CF', 'country_status' => 'A'],
            ['country_name' => 'Chad', 'country_iso' => 'TD', 'country_status' => 'A'],
            ['country_name' => 'Chile', 'country_iso' => 'CL', 'country_status' => 'A'],
            ['country_name' => 'China', 'country_iso' => 'CN', 'country_status' => 'A'],
            ['country_name' => 'Colombia', 'country_iso' => 'CO', 'country_status' => 'A'],
            ['country_name' => 'Comoros', 'country_iso' => 'KM', 'country_status' => 'A'],
            ['country_name' => 'Congo, Democratic Republic of the', 'country_iso' => 'CD', 'country_status' => 'A'],
            ['country_name' => 'Congo, Republic of the', 'country_iso' => 'CG', 'country_status' => 'A'],
            ['country_name' => 'Costa Rica', 'country_iso' => 'CR', 'country_status' => 'A'],
            ['country_name' => "Côte d'Ivoire", 'country_iso' => 'CI', 'country_status' => 'A'],
            ['country_name' => 'Croatia', 'country_iso' => 'HR', 'country_status' => 'A'],
            ['country_name' => 'Cuba', 'country_iso' => 'CU', 'country_status' => 'A'],
            ['country_name' => 'Cyprus', 'country_iso' => 'CY', 'country_status' => 'A'],
            ['country_name' => 'Czech Republic', 'country_iso' => 'CZ', 'country_status' => 'A'],
            ['country_name' => 'Denmark', 'country_iso' => 'DK', 'country_status' => 'A'],
            ['country_name' => 'Djibouti', 'country_iso' => 'DJ', 'country_status' => 'A'],
            ['country_name' => 'Dominica', 'country_iso' => 'DM', 'country_status' => 'A'],
            ['country_name' => 'Dominican Republic', 'country_iso' => 'DO', 'country_status' => 'A'],
            ['country_name' => 'Ecuador', 'country_iso' => 'EC', 'country_status' => 'A'],
            ['country_name' => 'Egypt', 'country_iso' => 'EG', 'country_status' => 'A'],
            ['country_name' => 'El Salvador', 'country_iso' => 'SV', 'country_status' => 'A'],
            ['country_name' => 'Equatorial Guinea', 'country_iso' => 'GQ', 'country_status' => 'A'],
            ['country_name' => 'Eritrea', 'country_iso' => 'ER', 'country_status' => 'A'],
            ['country_name' => 'Estonia', 'country_iso' => 'EE', 'country_status' => 'A'],
            ['country_name' => 'Eswatini', 'country_iso' => 'SZ', 'country_status' => 'A'],
            ['country_name' => 'Ethiopia', 'country_iso' => 'ET', 'country_status' => 'A'],
            ['country_name' => 'Fiji', 'country_iso' => 'FJ', 'country_status' => 'A'],
            ['country_name' => 'Finland', 'country_iso' => 'FI', 'country_status' => 'A'],
            ['country_name' => 'France', 'country_iso' => 'FR', 'country_status' => 'A'],
            ['country_name' => 'Gabon', 'country_iso' => 'GA', 'country_status' => 'A'],
            ['country_name' => 'Gambia', 'country_iso' => 'GM', 'country_status' => 'A'],
            ['country_name' => 'Georgia', 'country_iso' => 'GE', 'country_status' => 'A'],
            ['country_name' => 'Germany', 'country_iso' => 'DE', 'country_status' => 'A'],
            ['country_name' => 'Ghana', 'country_iso' => 'GH', 'country_status' => 'A'],
            ['country_name' => 'Greece', 'country_iso' => 'GR', 'country_status' => 'A'],
            ['country_name' => 'Grenada', 'country_iso' => 'GD', 'country_status' => 'A'],
            ['country_name' => 'Guatemala', 'country_iso' => 'GT', 'country_status' => 'A'],
            ['country_name' => 'Guinea', 'country_iso' => 'GN', 'country_status' => 'A'],
            ['country_name' => 'Guinea-Bissau', 'country_iso' => 'GW', 'country_status' => 'A'],
            ['country_name' => 'Guyana', 'country_iso' => 'GY', 'country_status' => 'A'],
            ['country_name' => 'Haiti', 'country_iso' => 'HT', 'country_status' => 'A'],
            ['country_name' => 'Honduras', 'country_iso' => 'HN', 'country_status' => 'A'],
            ['country_name' => 'Hungary', 'country_iso' => 'HU', 'country_status' => 'A'],
            ['country_name' => 'Iceland', 'country_iso' => 'IS', 'country_status' => 'A'],
            ['country_name' => 'India', 'country_iso' => 'IN', 'country_status' => 'A'],
            ['country_name' => 'Indonesia', 'country_iso' => 'ID', 'country_status' => 'A'],
            ['country_name' => 'Iran', 'country_iso' => 'IR', 'country_status' => 'A'],
            ['country_name' => 'Iraq', 'country_iso' => 'IQ', 'country_status' => 'A'],
            ['country_name' => 'Ireland', 'country_iso' => 'IE', 'country_status' => 'A'],
            ['country_name' => 'Israel', 'country_iso' => 'IL', 'country_status' => 'A'],
            ['country_name' => 'Italy', 'country_iso' => 'IT', 'country_status' => 'A'],
            ['country_name' => 'Jamaica', 'country_iso' => 'JM', 'country_status' => 'A'],
            ['country_name' => 'Japan', 'country_iso' => 'JP', 'country_status' => 'A'],
            ['country_name' => 'Jordan', 'country_iso' => 'JO', 'country_status' => 'A'],
            ['country_name' => 'Kazakhstan', 'country_iso' => 'KZ', 'country_status' => 'A'],
            ['country_name' => 'Kenya', 'country_iso' => 'KE', 'country_status' => 'A'],
            ['country_name' => 'Kiribati', 'country_iso' => 'KI', 'country_status' => 'A'],
            ['country_name' => 'Korea, Democratic People\'s Republic of', 'country_iso' => 'KP', 'country_status' => 'A'],
            ['country_name' => 'Korea, Republic of', 'country_iso' => 'KR', 'country_status' => 'A'],
            ['country_name' => 'Kuwait', 'country_iso' => 'KW', 'country_status' => 'A'],
            ['country_name' => 'Kyrgyzstan', 'country_iso' => 'KG', 'country_status' => 'A'],
            ['country_name' => 'Lao People\'s Democratic Republic', 'country_iso' => 'LA', 'country_status' => 'A'],
            ['country_name' => 'Latvia', 'country_iso' => 'LV', 'country_status' => 'A'],
            ['country_name' => 'Lebanon', 'country_iso' => 'LB', 'country_status' => 'A'],
            ['country_name' => 'Lesotho', 'country_iso' => 'LS', 'country_status' => 'A'],
            ['country_name' => 'Liberia', 'country_iso' => 'LR', 'country_status' => 'A'],
            ['country_name' => 'Libya', 'country_iso' => 'LY', 'country_status' => 'A'],
            ['country_name' => 'Liechtenstein', 'country_iso' => 'LI', 'country_status' => 'A'],
            ['country_name' => 'Lithuania', 'country_iso' => 'LT', 'country_status' => 'A'],
            ['country_name' => 'Luxembourg', 'country_iso' => 'LU', 'country_status' => 'A'],
            ['country_name' => 'Madagascar', 'country_iso' => 'MG', 'country_status' => 'A'],
            ['country_name' => 'Malawi', 'country_iso' => 'MW', 'country_status' => 'A'],
            ['country_name' => 'Malaysia', 'country_iso' => 'MY', 'country_status' => 'A'],
            ['country_name' => 'Maldives', 'country_iso' => 'MV', 'country_status' => 'A'],
            ['country_name' => 'Mali', 'country_iso' => 'ML', 'country_status' => 'A'],
            ['country_name' => 'Malta', 'country_iso' => 'MT', 'country_status' => 'A'],
            ['country_name' => 'Marshall Islands', 'country_iso' => 'MH', 'country_status' => 'A'],
            ['country_name' => 'Mauritania', 'country_iso' => 'MR', 'country_status' => 'A'],
            ['country_name' => 'Mauritius', 'country_iso' => 'MU', 'country_status' => 'A'],
            ['country_name' => 'Mexico', 'country_iso' => 'MX', 'country_status' => 'A'],
            ['country_name' => 'Micronesia (Federated States of)', 'country_iso' => 'FM', 'country_status' => 'A'],
            ['country_name' => 'Moldova (Republic of)', 'country_iso' => 'MD', 'country_status' => 'A'],
            ['country_name' => 'Monaco', 'country_iso' => 'MC', 'country_status' => 'A'],
            ['country_name' => 'Mongolia', 'country_iso' => 'MN', 'country_status' => 'A'],
            ['country_name' => 'Montenegro', 'country_iso' => 'ME', 'country_status' => 'A'],
            ['country_name' => 'Morocco', 'country_iso' => 'MA', 'country_status' => 'A'],
            ['country_name' => 'Mozambique', 'country_iso' => 'MZ', 'country_status' => 'A'],
            ['country_name' => 'Myanmar', 'country_iso' => 'MM', 'country_status' => 'A'],
            ['country_name' => 'Namibia', 'country_iso' => 'NA', 'country_status' => 'A'],
            ['country_name' => 'Nauru', 'country_iso' => 'NR', 'country_status' => 'A'],
            ['country_name' => 'Nepal', 'country_iso' => 'NP', 'country_status' => 'A'],
            ['country_name' => 'Netherlands', 'country_iso' => 'NL', 'country_status' => 'A'],
            ['country_name' => 'New Zealand', 'country_iso' => 'NZ', 'country_status' => 'A'],
            ['country_name' => 'Nicaragua', 'country_iso' => 'NI', 'country_status' => 'A'],
            ['country_name' => 'Niger', 'country_iso' => 'NE', 'country_status' => 'A'],
            ['country_name' => 'Nigeria', 'country_iso' => 'NG', 'country_status' => 'A'],
            ['country_name' => 'North Macedonia', 'country_iso' => 'MK', 'country_status' => 'A'],
            ['country_name' => 'Norway', 'country_iso' => 'NO', 'country_status' => 'A'],
            ['country_name' => 'Oman', 'country_iso' => 'OM', 'country_status' => 'A'],
            ['country_name' => 'Pakistan', 'country_iso' => 'PK', 'country_status' => 'A'],
            ['country_name' => 'Palau', 'country_iso' => 'PW', 'country_status' => 'A'],
            ['country_name' => 'Palestine, State of', 'country_iso' => 'PS', 'country_status' => 'A'],
            ['country_name' => 'Panama', 'country_iso' => 'PA', 'country_status' => 'A'],
            ['country_name' => 'Papua New Guinea', 'country_iso' => 'PG', 'country_status' => 'A'],
            ['country_name' => 'Paraguay', 'country_iso' => 'PY', 'country_status' => 'A'],
            ['country_name' => 'Peru', 'country_iso' => 'PE', 'country_status' => 'A'],
            ['country_name' => 'Philippines', 'country_iso' => 'PH', 'country_status' => 'A'],
            ['country_name' => 'Poland', 'country_iso' => 'PL', 'country_status' => 'A'],
            ['country_name' => 'Portugal', 'country_iso' => 'PT', 'country_status' => 'A'],
            ['country_name' => 'Qatar', 'country_iso' => 'QA', 'country_status' => 'A'],
            ['country_name' => 'Romania', 'country_iso' => 'RO', 'country_status' => 'A'],
            ['country_name' => 'Russian Federation', 'country_iso' => 'RU', 'country_status' => 'A'],
            ['country_name' => 'Rwanda', 'country_iso' => 'RW', 'country_status' => 'A'],
            ['country_name' => 'Saint Kitts and Nevis', 'country_iso' => 'KN', 'country_status' => 'A'],
            ['country_name' => 'Saint Lucia', 'country_iso' => 'LC', 'country_status' => 'A'],
            ['country_name' => 'Saint Vincent and the Grenadines', 'country_iso' => 'VC', 'country_status' => 'A'],
            ['country_name' => 'Samoa', 'country_iso' => 'WS', 'country_status' => 'A'],
            ['country_name' => 'San Marino', 'country_iso' => 'SM', 'country_status' => 'A'],
            ['country_name' => 'Sao Tome and Principe', 'country_iso' => 'ST', 'country_status' => 'A'],
            ['country_name' => 'Saudi Arabia', 'country_iso' => 'SA', 'country_status' => 'A'],
            ['country_name' => 'Senegal', 'country_iso' => 'SN', 'country_status' => 'A'],
            ['country_name' => 'Serbia', 'country_iso' => 'RS', 'country_status' => 'A'],
            ['country_name' => 'Seychelles', 'country_iso' => 'SC', 'country_status' => 'A'],
            ['country_name' => 'Sierra Leone', 'country_iso' => 'SL', 'country_status' => 'A'],
            ['country_name' => 'Singapore', 'country_iso' => 'SG', 'country_status' => 'A'],
            ['country_name' => 'Slovakia', 'country_iso' => 'SK', 'country_status' => 'A'],
            ['country_name' => 'Slovenia', 'country_iso' => 'SI', 'country_status' => 'A'],
            ['country_name' => 'Solomon Islands', 'country_iso' => 'SB', 'country_status' => 'A'],
            ['country_name' => 'Somalia', 'country_iso' => 'SO', 'country_status' => 'A'],
            ['country_name' => 'South Africa', 'country_iso' => 'ZA', 'country_status' => 'A'],
            ['country_name' => 'South Sudan', 'country_iso' => 'SS', 'country_status' => 'A'],
            ['country_name' => 'Spain', 'country_iso' => 'ES', 'country_status' => 'A'],
            ['country_name' => 'Sri Lanka', 'country_iso' => 'LK', 'country_status' => 'A'],
            ['country_name' => 'Sudan', 'country_iso' => 'SD', 'country_status' => 'A'],
            ['country_name' => 'Suriname', 'country_iso' => 'SR', 'country_status' => 'A'],
            ['country_name' => 'Sweden', 'country_iso' => 'SE', 'country_status' => 'A'],
            ['country_name' => 'Switzerland', 'country_iso' => 'CH', 'country_status' => 'A'],
            ['country_name' => 'Syrian Arab Republic', 'country_iso' => 'SY', 'country_status' => 'A'],
            ['country_name' => 'Tajikistan', 'country_iso' => 'TJ', 'country_status' => 'A'],
            ['country_name' => 'Tanzania, United Republic of', 'country_iso' => 'TZ', 'country_status' => 'A'],
            ['country_name' => 'Thailand', 'country_iso' => 'TH', 'country_status' => 'A'],
            ['country_name' => 'Timor-Leste', 'country_iso' => 'TL', 'country_status' => 'A'],
            ['country_name' => 'Togo', 'country_iso' => 'TG', 'country_status' => 'A'],
            ['country_name' => 'Tonga', 'country_iso' => 'TO', 'country_status' => 'A'],
            ['country_name' => 'Trinidad and Tobago', 'country_iso' => 'TT', 'country_status' => 'A'],
            ['country_name' => 'Tunisia', 'country_iso' => 'TN', 'country_status' => 'A'],
            ['country_name' => 'Turkey', 'country_iso' => 'TR', 'country_status' => 'A'],
            ['country_name' => 'Turkmenistan', 'country_iso' => 'TM', 'country_status' => 'A'],
            ['country_name' => 'Tuvalu', 'country_iso' => 'TV', 'country_status' => 'A'],
            ['country_name' => 'Uganda', 'country_iso' => 'UG', 'country_status' => 'A'],
            ['country_name' => 'Ukraine', 'country_iso' => 'UA', 'country_status' => 'A'],
            ['country_name' => 'United Arab Emirates', 'country_iso' => 'AE', 'country_status' => 'A'],
            ['country_name' => 'United Kingdom of Great Britain and Northern Ireland', 'country_iso' => 'GB', 'country_status' => 'A'],
            ['country_name' => 'United States of America', 'country_iso' => 'US', 'country_status' => 'A'],
            ['country_name' => 'Uruguay', 'country_iso' => 'UY', 'country_status' => 'A'],
            ['country_name' => 'Uzbekistan', 'country_iso' => 'UZ', 'country_status' => 'A'],
            ['country_name' => 'Vanuatu', 'country_iso' => 'VU', 'country_status' => 'A'],
            ['country_name' => 'Venezuela (Bolivarian Republic of)', 'country_iso' => 'VE', 'country_status' => 'A'],
            ['country_name' => 'Viet Nam', 'country_iso' => 'VN', 'country_status' => 'A'],
            ['country_name' => 'Yemen', 'country_iso' => 'YE', 'country_status' => 'A'],
            ['country_name' => 'Zambia', 'country_iso' => 'ZM', 'country_status' => 'A'],
            ['country_name' => 'Zimbabwe', 'country_iso' => 'ZW', 'country_status' => 'A'],
        ];

        DB::table('reach_passport')->insert($countries);
    }
}

